clear
echo Starting install...
echo Запуск установки...
sleep 2
clear
echo Step 1. Update and upgrade lib's
echo Шаг 1. Обновление и апгрейт библиотек
sleep 2
sudo apt update
sudo apt full-upgrade
clear
echo Installing...
echo Установка...
echo ________________________
echo Step 2. Installing tasksel for setup VNC...
echo Шаг 2. Установка tasksel для настройки VNC...
sleep 2
sudo apt install tasksel
sudo tasksel install kubuntu-full
clear
echo Installing...
echo Установка...
echo ________________________
echo Step 3. Installing vnc...
echo Шаг 3. Установка vnc...
sudo apt install xfce4 xfce4-goodies
sudo apt install tightvncserver
clear
echo Installing...
echo Установка...
echo ________________________
echo Step 4. Setup VNC...
echo Шаг 4. Настройка VNC...
vncserver
vncserver -kill :1
mv ~/.vnc/xstartup ~/.vnc/xstartup.bak
wget https://raw.githubusercontent.com/AyonovDenizs/setup-kde-on-Ubuntu/ayden/xstartup
mv xstartup ~/.vnc/xstartup
sudo chmod +x ~/.vnc/xstartup
vncserver -localhost
echo "успешно установлено."
echo "Successfully installed."

